# Generated by Django 5.0.4 on 2024-05-19 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='takenbook',
            name='status',
            field=models.CharField(choices=[('Awaiting', 'Awaiting'), ('Taken', 'Taken')], default='Awaiting', max_length=10, verbose_name='Status'),
        ),
    ]
