# Generated by Django 5.0.4 on 2024-05-20 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_takenbook_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='takenbook',
            name='status',
            field=models.CharField(choices=[('Awaiting', 'Awaiting'), ('Taken', 'Taken')], default='Awaiting', max_length=10, verbose_name='Status'),
        ),
    ]
