# Generated by Django 5.0.4 on 2024-05-25 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_returnedbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='takenbook',
            name='status',
            field=models.CharField(choices=[('Awaiting', 'Awaiting'), ('Taken', 'Taken'), ('Returned', 'Returned')], default='Awaiting', max_length=10, verbose_name='Status'),
        ),
    ]
